ALTER TABLE "intelligence"."derived_features" DROP CONSTRAINT "chk_features_status_value";--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" DROP CONSTRAINT "chk_features_unit_bps";--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" DROP CONSTRAINT "chk_features_unit_bps2";--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" DROP CONSTRAINT "chk_features_unit_bps3";--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" DROP CONSTRAINT "chk_features_unit_ppm";--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" DROP CONSTRAINT "chk_features_unit_ppm2";--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" DROP CONSTRAINT "chk_features_unit_ppm3";--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" DROP CONSTRAINT "chk_features_unit_ppm4";--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" DROP CONSTRAINT "chk_features_scope_position";--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" DROP CONSTRAINT "chk_features_scope_volume";--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" DROP CONSTRAINT "chk_features_scope_other";--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ALTER COLUMN "input_observation_ids" SET DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ALTER COLUMN "rejected_observation_ids" SET DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "intelligence"."evidence_bundles" ALTER COLUMN "schema_version" SET DATA TYPE varchar(32);--> statement-breakpoint
ALTER TABLE "intelligence"."raw_observations" ALTER COLUMN "source_observation_key" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD COLUMN "warnings" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD COLUMN "reasons" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD CONSTRAINT "chk_features_status_value" CHECK ((("intelligence"."derived_features"."status" = 'UNAVAILABLE' AND "intelligence"."derived_features"."value" IS NULL) OR ("intelligence"."derived_features"."status" <> 'UNAVAILABLE' AND "intelligence"."derived_features"."value" IS NOT NULL)));--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD CONSTRAINT "chk_features_unit_bps" CHECK ((("intelligence"."derived_features"."feature_kind" = 'oracle_dex_divergence' AND "intelligence"."derived_features"."unit" = 'BPS') OR ("intelligence"."derived_features"."feature_kind" <> 'oracle_dex_divergence')));--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD CONSTRAINT "chk_features_unit_bps2" CHECK ((("intelligence"."derived_features"."feature_kind" = 'oracle_confidence_width' AND "intelligence"."derived_features"."unit" = 'BPS') OR ("intelligence"."derived_features"."feature_kind" <> 'oracle_confidence_width')));--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD CONSTRAINT "chk_features_unit_bps3" CHECK ((("intelligence"."derived_features"."feature_kind" = 'realized_volatility_1h' AND "intelligence"."derived_features"."unit" = 'BPS') OR ("intelligence"."derived_features"."feature_kind" <> 'realized_volatility_1h')));--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD CONSTRAINT "chk_features_unit_ppm" CHECK ((("intelligence"."derived_features"."feature_kind" = 'range_location' AND "intelligence"."derived_features"."unit" = 'PPM') OR ("intelligence"."derived_features"."feature_kind" <> 'range_location')));--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD CONSTRAINT "chk_features_unit_ppm2" CHECK ((("intelligence"."derived_features"."feature_kind" = 'distance_to_lower' AND "intelligence"."derived_features"."unit" = 'PPM') OR ("intelligence"."derived_features"."feature_kind" <> 'distance_to_lower')));--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD CONSTRAINT "chk_features_unit_ppm3" CHECK ((("intelligence"."derived_features"."feature_kind" = 'distance_to_upper' AND "intelligence"."derived_features"."unit" = 'PPM') OR ("intelligence"."derived_features"."feature_kind" <> 'distance_to_upper')));--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD CONSTRAINT "chk_features_unit_ppm4" CHECK ((("intelligence"."derived_features"."feature_kind" = 'volume_liquidity_ratio_24h' AND "intelligence"."derived_features"."unit" = 'PPM') OR ("intelligence"."derived_features"."feature_kind" <> 'volume_liquidity_ratio_24h')));--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD CONSTRAINT "chk_features_scope_position" CHECK (((("intelligence"."derived_features"."feature_kind" IN ('range_location', 'distance_to_lower', 'distance_to_upper')) AND "intelligence"."derived_features"."pool_id" IS NOT NULL AND "intelligence"."derived_features"."position_id" IS NOT NULL) OR ("intelligence"."derived_features"."feature_kind" NOT IN ('range_location', 'distance_to_lower', 'distance_to_upper'))));--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD CONSTRAINT "chk_features_scope_volume" CHECK (((("intelligence"."derived_features"."feature_kind" = 'volume_liquidity_ratio_24h') AND "intelligence"."derived_features"."pool_id" IS NOT NULL AND "intelligence"."derived_features"."position_id" IS NULL) OR ("intelligence"."derived_features"."feature_kind" <> 'volume_liquidity_ratio_24h')));--> statement-breakpoint
ALTER TABLE "intelligence"."derived_features" ADD CONSTRAINT "chk_features_scope_other" CHECK (((("intelligence"."derived_features"."feature_kind" IN ('oracle_dex_divergence', 'oracle_confidence_width', 'realized_volatility_1h')) AND "intelligence"."derived_features"."pool_id" IS NULL AND "intelligence"."derived_features"."position_id" IS NULL) OR ("intelligence"."derived_features"."feature_kind" NOT IN ('oracle_dex_divergence', 'oracle_confidence_width', 'realized_volatility_1h'))));