import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const SCHEMA_PATH = fileURLToPath(
  new URL("../schemas/regime-engine/evidence-bundle.v1/schema.json", import.meta.url)
);
const OUTPUT_DIR = fileURLToPath(new URL("../src/contracts/generated", import.meta.url));
const OUTPUT_FILE = join(OUTPUT_DIR, "evidence-bundle-v1.ts");

function computeSha256(content: string): string {
  return createHash("sha256").update(content, "utf-8").digest("hex");
}

async function main(): Promise<void> {
  const schemaContent = await readFile(SCHEMA_PATH, "utf-8");
  const schemaSha256 = computeSha256(schemaContent);

  const tsDeclaration = execSync(`npx --yes json-schema-to-typescript@15.0.4 "${SCHEMA_PATH}"`, {
    encoding: "utf-8"
  });

  const cliBannerRegex =
    /\/\* eslint-disable \*\/\n\s*\/\*\*\n\s*\*\s*This file was automatically generated[\s\S]*?\*\/\n/;
  const tsDeclarationWithoutBanner = tsDeclaration.replace(cliBannerRegex, "");

  const output = `export const SCHEMA_SHA256 = "${schemaSha256}";

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run pnpm contract:evidence-bundle:generate to regenerate this file.
 */

${tsDeclarationWithoutBanner}`;

  await mkdir(OUTPUT_DIR, { recursive: true });
  await writeFile(OUTPUT_FILE, output, "utf-8");

  console.log(`Generated ${OUTPUT_FILE}`);
  console.log(`Schema SHA256: ${schemaSha256}`);
}

main().catch((err) => {
  console.error("Error generating EvidenceBundleV1:", err);
  process.exit(1);
});
